### ISSUE TITLE
Delayed retries

### ISSUE THREAD

**Issue by Zehelein** [guidesmiths/rascal#101]
I am trying the advanced example and the retries do not seem to use any delay.

My steps were:
- clone this repository
- `npm i`
- `npm run docker`
- `npm run test` - all tests are green
- `node ./examples/advanced/cluster.js`

Console output:

```
Saving user: Katherine_Garcia
Saving user: Don_Bensi
Deleting user: Marion_Moore
Saving user: Carl_Sugimoto
Saving user: Anthony_Falsini
Deleting user: Leroy_Ferrer
C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11
            if (user.crash) throw new Error('Crashing on user: ' + user.username)
                            ^

Error: Crashing on user: Leroy_Ferrer
    at Immediate.<anonymous> (C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11:35)
    at processImmediate (internal/timers.js:439:21)
Deleting user: Leroy_Ferrer
C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11
            if (user.crash) throw new Error('Crashing on user: ' + user.username)
                            ^

Error: Crashing on user: Leroy_Ferrer
    at Immediate.<anonymous> (C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11:35)
    at processImmediate (internal/timers.js:439:21)
Deleting user: Leroy_Ferrer
C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11
            if (user.crash) throw new Error('Crashing on user: ' + user.username)
                            ^

Error: Crashing on user: Leroy_Ferrer
    at Immediate.<anonymous> (C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11:35)
    at processImmediate (internal/timers.js:439:21)
Deleting user: Leroy_Ferrer
C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11
            if (user.crash) throw new Error('Crashing on user: ' + user.username)
                            ^

Error: Crashing on user: Leroy_Ferrer
    at Immediate.<anonymous> (C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11:35)
    at processImmediate (internal/timers.js:439:21)
Deleting user: Leroy_Ferrer
C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11
            if (user.crash) throw new Error('Crashing on user: ' + user.username)
                            ^

Error: Crashing on user: Leroy_Ferrer
    at Immediate.<anonymous> (C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11:35)
    at processImmediate (internal/timers.js:439:21)
Deleting user: Leroy_Ferrer
C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11
            if (user.crash) throw new Error('Crashing on user: ' + user.username)
                            ^

Error: Crashing on user: Leroy_Ferrer
    at Immediate.<anonymous> (C:\Projects\rascal\examples\advanced\handlers\deleteUser.js:11:35)
    at processImmediate (internal/timers.js:439:21)
Redeliveries Exceeded Message 429c5cf5-808f-49e3-baf0-9f698cd778fd has exceeded 5 redeliveries
```

All of this is happening without any delay. Am I missing any specific setup? According to the configuration in the advanced example I would assume there is a one minute delay between retries.

**Comment by cressie176** [comment]
Hi @Zehelein,

The advanced example demonstrates many different error scenarios. The one you're seeing is what happens when a message  repeatedly crashes your application. The example is configured to nack those messages after 5 redeliveries. This type of handling is important as unless a 'poison' message is acked/nacked it will continue to be redelivered, crashing your application over and over again.

The delayed retry occurs when the example [simulates](https://github.com/guidesmiths/rascal/blob/master/examples/advanced/handlers/saveUser.js#L16-L20) what it considers to be a recoverable error. You can `console.error(err)` [here](https://github.com/guidesmiths/rascal/blob/master/examples/advanced/index.js#L28) to make this more obvious.

I've run locally and can see messages being routed to the delay queue.

<img width="846" alt="Screenshot 2020-06-29 at 18 24 53" src="https://user-images.githubusercontent.com/229672/86036481-d9e64000-ba35-11ea-975d-d2485ec4f727.png">

I could also see the same user being retried later, so confident the example still works.

**Comment by Zehelein** [comment]
Hi,

thank you for your very quick and great answer! Yes this makes sense. I mixed both concepts about retries (app did not crash and we can on our own decide how to proceed with the message) and redeliveries (a message crashes the applicatoin). But it works exactly as you describe. 

So poisonous messages will be re-delivered immediately. I see no option to add a delay for that - they will just be added back to the beginning of the queue, will be redelivered up to the configured "limit". If I would like to have also delayed retries I would need a try/catch block inside the full handler function, catch the poisonous message on my own and then decide if I want a (delayed) retry or not.

**Comment by cressie176** [comment]
Hi @Zehelein,

Glad things worked out. You are right, there's no way to stop a poisonous message being redelivered, other than to configured the consumer to autoack, in which case RabbitMQ removes the message from the queue before it is delivered. Of course the problem with this is that if something goes wrong, there is no automated retry and the message is lost.

> If I would like to have also delayed retries I would need a try/catch block inside the full handler function, catch the poisonous message on my own and then decide if I want a (delayed) retry or not.

The snag here is that as careful as you are, there's always the chance of a bug meaning that something in the catch goes wrong. They could also be uncatchable errors, e.g. maybe something in the message triggers a bug in node, or the message is so big it consumes exceeds a memory threshold. Poison messages don't happen very often, but they're usually not recoverable, so the best course of action is to detect them, and nack them to a dead letter queue.

**Comment by Zehelein** [comment]
thanks for your insights - this helps :-)

**Comment by Zehelein** [comment]
I wanted to add one input: I was trying it out now without using clusters and just running the index.js with the redis counter implementation. When using cluster all was fine but when starting index.js directly the poisonous message would kill the process (which is fine). But the redis counter was then not increased. That might be obvious for some but maybe you can adjust your example to cleanly shutdown the broker:

```js
    process
      .on("SIGINT", function () {
        broker.shutdown(function () {
          process.exit();
        });
      })
      .on("unhandledRejection", (reason, p) => {
        console.error(reason, "Unhandled Rejection at Promise", p);
        broker.shutdown(function () {
          process.exit();
        });
      })
      .on("uncaughtException", (err) => {
        console.error(err, "Uncaught Exception thrown");
        broker.shutdown(function () {
          process.exit();
        });
      });
```

**Comment by Zehelein** [comment]
And me again - but this time I think I found one error in the advanced example.

In my tests the broker.subscribe ... `.on("message"...` always runs into the error scenario. Because the saveUser and deleteUser will always send an error. Be it on purpose for error cases 5/7 in saveUser or in the line 
`publication.on("success", cb).on("error", console.error);`

The `"success", cb` part will forward the parameters of the ".on" callback to the `cb` function. This means the index.js part from above will receive a UUID string as error which is not null/undefined. I think those lines in save/create Uers should rather be:
`publication.on("success", () => cb()).on("error", console.error);`

**Comment by cressie176** [comment]
Hi @Zehelein, good spot re the success callback. Thanks for reporting it. I'll fix shortly.

**Comment by cressie176** [comment]
I'm a little confused by the following...

> But the redis counter was then not increased. That might be obvious for some but maybe you can adjust your example to cleanly shutdown the broker (not sure about process.exit or rather rethrow the error):

Do you mean there are two separate concerns...

1. The redis counter was not updated
2. The example would be improved with graceful shutdown

Assuming so, then I can probably explain the first one...

When a message is delivered for the first time and crashes the app, rascal does nothing. When you think about it, it can't - even with try/catch as discussed earlier.

However when a message is redelivered after being rolled back, RabbitMQ adds a redelivery flag. Unfortunately this is a boolean rather than a count of the failed attempts.

When Rascal sees a message has been redelivered, it starts counting the redeliveries (using whatever counter is configured).So you will only see the count incremented the second time the message crashes the application.

Re (2) I agree this would improve the example. Thanks for the suggestion.  I would also add `SIGTERM` too. Happy to accept a PR, but otherwise I'll make the changes in due course.

**Comment by Zehelein** [comment]
Ah yes - you are right. It is handled on the second start of the application, it is then added as a redis counter and correctly exceeded after the 5th retry.

And sure - creating a PR for this change. The `() => cb` one I saw that you already fixed it - thanks!
