### ISSUE TITLE
RPC / Reply to behaviour

### ISSUE THREAD

**Issue by mikeryancodes** [guidesmiths/rascal#105]
Following some discussions with @cressie176, we would like to enable RPC / Reply to behaviour

The API would look something like this:
```javascript
const publication = await broker.publish('my-publication', content);
publication.replySubscription.on('message', (msg, content) => {
  await doSomething(content);
  await publication.replySubscription.cancel();
});
```
Under the hood:
- When creating a channel, we have the channel consume from the pseudo-queue [`amq.rabbitmq.direct-reply-to`](https://www.rabbitmq.com/direct-reply-to.html#usage)
- We will create a `correlationId` for each message that is published, and that `correlationId` will also be available to `publication`
- Attaching an event handler to `publication.replySubscription` places into a map keyed by `correlationId` for direct reply-to events on the channel

The message consumer can reply by using the `replyTo` property on the incoming message. It would publish to the default exchange using the `replyTo` property as the routing key (see the link above), and passing the `correlationId` as an option.

Cancelling the `replySubscription` would remove its event handlers from the map.

**Comment by cressie176** [comment]
How about...

1. The publication can be configured with `replyTo: amq.rabbitmq.reply-to` or perhaps `directReplies: true`
1. The API looks like
    ```
    const publication = await broker.publish('my-publication', content);
    publication.replies.on('message', (message, content) => {
      // Note there would be no third ackOrNack parameter because direct reply-to "queues" are auto-ack
      // Handle message(s)
      publication.replies.cancel();
    }).on('error', (err) => {
      // Handle error
    })
```
1. Because Rascal uses a channel pool, each would need to consume from the `amq.rabbitmq.reply-to` pseudo queue, then invoke the correct publication's reply message handler
1. To do this we could listen for the `newListener` event when the 'message' handler was added, and store the message handler, keyed with a correlationId controlled by the publication (assuming one wasn't already present in the message)
1. On receiving a reply, Rascal would use the correlationId in the reply to find and invoke the correct publication message handler
1. We should support multiple replies to the same message handler
1. We must provide a way for the user to cancel / remove the message handler to avoid memory leaks
1. If the message handler does not exist, we should do nothing (it could have been cancelled)
1. If the publication does not include reply config, the `publication.replies` property should be undefined.

**Comment by crobinson42** [comment]
I am very interested in this functionality too - since the PR was rejected I'm rolling my own using another amqp lib. Watching rascal from a distance 👁️ 👍
