### ISSUE TITLE
Cluster Configuration - reconnect and retry

### ISSUE THREAD

**Issue by willthrom** [guidesmiths/rascal#119]
Hi,

Doing some HA testing I notice very odd behaviours (10.2.1)

when configuring multiple connections, calling broker.getConnections(), only returns one. Using Random strategy could be any of the Cluster. (I was expecting 3 but it is not an issue).
However, if I killed the RabbitMQ node where the broker is connected, it keeps trying to connect to that node, instead of connecting to a different one.
```
Operation failed: QueueDeclare; 404 (NOT-FOUND) with message \"NOT_FOUND - home node 'rabbit@rabbit2' of durable queue 'XXXYYYY-DEPOSIT-REQUESTS-QUEUE' in vhost '/' is down or inaccessible\" / amqp://guest:***@rabbitmq.infrastructure:5673"}
```
If I start again the killed Node (rabbit2), Rascal reconnects. 

I tried to kill/restart the node and seems to work however I notice that I see in the RabbitMQ Web the connection being established from Rascal (or ampqlib) and Rascal still printing some errors:

```
10:39:38 "msg":"Broker errorError: write ECONNRESET / amqp://guest:***@rabbitmq.infrastructure:5673"}
10:39:38 "msg":"Subscriber error"}
10:39:38 "msg":"Subscriber error"}
10:39:42 "msg":"Broker errorError: Operation failed: QueueDeclare; 404 (NOT-FOUND) ...  amqp://guest:***@rabbitmq.infrastructure:5673"}
10:39:46 "msg":"Broker errorError: Operation failed: QueueDeclare; 404 (NOT-FOUND) ...  amqp://guest:***@rabbitmq.infrastructure:5673"}
10:39:50 "msg":"Broker errorError: Operation failed: QueueDeclare; 404 (NOT-FOUND) ...  amqp://guest:***@rabbitmq.infrastructure:5673"}
10:39:55 "msg":"Broker errorError: Operation failed: QueueDeclare; 404 (NOT-FOUND) ...  amqp://guest:***@rabbitmq.infrastructure:5673"}
```

In 10:39:38  is when I see in RabbitMQ Control Panel the connection appearing but it gets disconnected, and created again in 10:39:55

10:39:38 "msg":"Subscriber error"} are from this:
```
const subscription = await broker.subscribe(s)
    subscription
      .on('message', cb)      
      .on('error', (err) => {
        logger.error('Subscriber error: ', err)
      })
```

If I restart the application, without starting again the RabbitMQ killed node, the application fails, instead of trying a different node:

```
18/08/2020 11:14:52{" "msg":"Error creating Broker: Operation failed: QueueDeclare; 404 (NOT-FOUND) with message \"NOT_FOUND - home node 'rabbit@rabbit2' of durable queue 'XXX-REQUESTS-QUEUE' in vhost '/' is down or inaccessible\""}

```
I could understand Rascal not creating the broker if only one connection was configured but with a cluster of 3 nodes.. It is not trying the other 2. Or I have an issue in the config:

However, If I configured a Mirror Queue and start doing request to the broker, if I kill one of the node (even the one with the active connection) Rascal connect to a different node automatically and seems to work, from a while. If I continue killing master queue node and starting the previous one, at some point no more connections....
I mean:  Node1,Node2 (Master queue), Node3 (replicated queue)
Kill Node2, Rascal connect automatically to Node 3 (becoming master queue), and Node 1 become replicated queue).
Doing this a couple of time ends up in no more re-connections....

**Config:**
```
"vhosts": {
		"/": {
			"connections": [
				{
					"hostname": "rabbitmq.infrastructure",
					"port": "5672",
					"user": "guest",
					"password": "guest",
					"retry": {
						"min": 1000,
						"max": 5000,
						"strategy": "linear"
					}
				},
				{
					"hostname": "rabbitmq.infrastructure",
					"port": "5673",
					"user": "guest",
					"password": "guest",
					"retry": {
						"min": 1000,
						"max": 5000,
						"strategy": "linear"
					}
				},
				{
					"hostname": "rabbitmq.infrastructure",
					"port": "5674",
					"user": "guest",
					"password": "guest",
					"retry": {
						"min": 1000,
						"max": 5000,
						"strategy": "linear"
					}
				}
			],
```

**Comment by cressie176** [comment]
> when configuring multiple connections, calling broker.getConnections(), only returns one. Using Random strategy could be any of the Cluster. (I was expecting 3 but it is not an issue).

[broker.getConnections()](https://github.com/guidesmiths/rascal#brokergetconnections)  returns details for the connections that were established. For example, if you had two vhosts "A" and "B", each running in a cluster of 3 nodes, "server1", "server2", "server3", then you should expect to get two records back.

```
[
  { "vhost": "A", "connectionUrl": "amqp://guest:***@server1:5672/A" }
  { "vhost": "B", "connectionUrl": "amqp://guest:***@server3:5672/B" }
]
```

> However, if I killed the RabbitMQ node where the broker is connected, it keeps trying to connect to that node, instead of connecting to a different one. If I start again the killed Node (rabbit2), Rascal reconnects.

You might want to check rascal's debug to confirm this. Run with the environment variable `DEBUG` set to `rascal:*`. The reason i say this is the error message your reported leaves might not mean what you think it means...
```
Operation failed: QueueDeclare; 404 (NOT-FOUND) with message \"NOT_FOUND - home node 'rabbit@rabbit2' of durable queue 'XXXYYYY-DEPOSIT-REQUESTS-QUEUE' in vhost '/' is down or inaccessible\" / amqp://guest:***@rabbitmq.infrastructure:5673"}
```

This tells me that Rascal successfully connected to`rabbitmq.infrastructure:5673`, but when failed to declare queue `XXXYYYY-DEPOSIT-REQUESTS-QUEUE'` with a *home node of rabbit@rabbit2* because the default vhost was inaccessible. Mirrored queues have a home node, which may not be the node you are connecting to. To get as far as declaring the queue, rascal must have at connected.

If you want to get familiar with how Rascal manages connections my suggestion is to start with a [simpler](https://github.com/guidesmiths/rascal/tree/master/examples/simple) config, pointing to a local docker container. Run with `DEBUG=rascal:*` and try killing or pausing the container. You should see Rascal notice the problem (it takes longer with pause), and attempt to reconnect. Once you have that working try switching to a clustered connection by specifying an array of hosts resolving to the same broker, e.g. `localhost:5672` and `127.0.0.1:5762`. Using the default config, you should see rascal randomise the host list on startup, then cycle through those hosts until you restart / resume the container.

Once you have this working, try with a more realistic environment and with the HA/mirrored queues

**Comment by willthrom** [comment]
I am already running a rabbitMQ cluster in Docker.

all the comments above were killing the different service (nodes) of rabbitMQ.

I will enable DEBUG rascal because what it might happen is one of those Random error doesn´t have a replicate of that queue as I am not mirroring to all the nodes (Replica 1).

If that is the case, I might need to only play with RabbitMQ configuration to replicate to specific nodes where the queues are replicated. Or add a loggic in top of Rascal to retry to connect until the queue is found. (random node).

**Comment by willthrom** [comment]
I gave it another thought was you said about the Queue not existing in that node, and two things:

that queue in the logs "XXXYYYY-DEPOSIT-REQUESTS-QUEUE" is created by the broker config.
```
queues: [
    DEPOSIT_REQUEST_QUEUE,
    WITHDRAW_REQUEST_QUEUE
  ],
```
so the error: 
```
Broker errorError: Operation failed: QueueDeclare; 404 (NOT-FOUND) with message \"NOT_FOUND - home node 'rabbit@rabbit2' of durable queue 'XXXTTTT-DEPOSIT-REQUESTS-QUEUE' in vhost '/' is down or inaccessible\" / amqp://guest:***@rabbitmq.infrastructure:5673"}
```
shouldn't happen unless the QUEUE is not created again after reconnect.  This queue is NOT Mirrored (HA) though.
Could it be the code assume after restarting the node rabbit2 the queue should be there because of the Durable?
Docker service stop might clean the queue from the "durable" stage.....

What I cannot understand is,, when I restart the APP, if I keep the rabbit2 down,  Rascal is not connecting printing the same error again and again...


I will enable DEBUG and attached it tomorrow.

**Comment by willthrom** [comment]
I configured the replications differently so all the queues configured in Rascal are replicated.

I have other issues with performance and crashing but I will created them separately.

Thanks
