### ISSUE TITLE
Not able to send content of subscribe.on(“message”) back to callee methods using rascal in nodeJS

### ISSUE THREAD

**Issue by mayankmike86** [guidesmiths/rascal#128]
I am using async/await model and implemented subscribing messages of a subscription using Rascal lib in NodeJS. The problem I am facing is that , I am getting the content from the subscription but not able to send back the content to callee method.

```js
module.exports = class RabbitmqClient {
    constructor(options) {
        this.options = options
    }

    async subscribe(broker,subscription) {
            try {
                logger.info(`Subscribing Messages for : ${subscription}`);
                const result = await broker.subscribe(subscription);
                await result.on('message', (message, content, ackOrNack) => {
                    //this logger is getting logged at very end of the flow.
                    logger.info(content)
                    return Promise.resolve(content);
                  }).on('error', (error) => {
                    var errMessage = "error occured during subscription process.."+error
                    logger.error('Error is: ', errMessage);
                    throw error;
                  });
                  // Execution jumps here and not waiting for above result.on to get process rather return from here and getting empty results in callee method
                  logger.debug("Subscription process ended succesfully..");
            } catch (err) {
                logger.error(`Error while subscribing the message ${JSON.stringify(err)}`);
                return Promise.reject(err);
            }
        }
}
```

So if I am calling above method from another file as

```js
var rabbitmqObj = new rabbitmqClient()
var result = await rabbitmqObj.subscribe(connection, subscribe);
logger.info("result found is: "+JSON.stringify(result));
```

The result is always undefined.

**Comment by cressie176** [comment]
Hi @mayankmike86,

Thanks for posting. Sorry to say, but I think you've misunderstood how [RabbitMQ consumers](https://www.rabbitmq.com/tutorials/amqp-concepts.html#consumers) and [Node event emitters](https://nodejs.org/api/events.html) work. The [RabbitMQ Concepts](https://www.rabbitmq.com/tutorials/amqp-concepts.html) and [amqplib Channel API](https://www.squaremobius.net/amqp.node/channel_api.html#channel_get) (the library underpinning Rascal) are must reads for anyone getting started, since RabbitMQ has significant differences to other message brokers. Also check out this [advanced example](https://github.com/guidesmiths/rascal/blob/master/examples/advanced/index.js) for how you could use Rascal in an application.

That said the big issue in your code centers around this line...

```js
await result.on('message', (message, content, ackOrNack) => {
```

`result` is an event emitter, and the `result.on` function is **synchronous**, returning the same instance of the emitter to enable chaining. The `message` event handler `(message, content, ackOrNack) => { ... }` is invoked whenever a message is received. i.e. it is designed to be called multiple times. Awaiting `result.on` will resolve immediately, hence why your subscribe function returns undefined. `return Promise.resolve(content)` will eventually be invoked whenever a message is delivered, but only after the `subscribe` function has already returned.  

Furthermore you've never called `ackOrNack` so the message will be left in an unacknowledged state on the broker, potentially blocking further messages (depending on your prefetch limit) and being rolled back/redelivered if when your application restarts.

From the above, it looks like you don't really want to consume an infinite stream of messages, rather you want to get a single message. Rascal doesn't support this directly, but it possible using [amqplib's channel.get](https://www.squaremobius.net/amqp.node/channel_api.html#channel_get). If this is all you want to do then forget about Rascal and just use amqplib. If you do intend to use pub/sub extensively, but also need `channel.get` you can obtain an amqplib connection using Rascal's [broker.connect](https://github.com/guidesmiths/rascal#connect), but you won't get the benefit of Rascal's connection recovery logic and should remember to disconnect.

**Comment by mayankmike86** [comment]
Hello cressie176 ,
Thanks for a quick reply. Please bear with me for any silly mistakes as i am new to Rabbitmq(Rascal).
The need here is to consume an infinite stream of messages in the subscription when ever my RabbitmqClient  subscribe() method is called. We are trying to use Rascal to subscribe and create an array of infinite stream of messages  and return the array to the callee method, is it possible to collect all the contents in the queue(i see only 10 messages, although there are more than 10 messages in my queue.). 
We have tried another way to achieve this but looks like my internal promise is never been resolved (may be due to listning event is not getting over).
```
async subscribe(broker,subscription, testCallback) {
         logger.info("inside subscribe client method")
        /*broker.subscribe(subscription, (err, subscription) => {
    if (err) throw err;
    subscription.on('message', testCallback).on('error', console.error);
  })*/

       logger.info("inside subscripber client call")
        var allresult = [];
        const result = await broker.subscribe(subscription);

        logger.info("gor broker subscription result: "+JSON.stringify(result))
        let promise = new Promise((resolve, reject) => {
                logger.info("inside promise")
      result.on('message', (message, content, ackOrNack) => {
              logger.info("satrted to listining to event messge");
        logger.info("message: "+JSON.stringify(message))
                             logger.info("content: "+JSON.stringify(content))
                allresult.push(content)
              logger.info("allresult: "+JSON.stringify(allresult))
             return (allresult);
              setTimeout(function(){
    resolve("Success!"); // Yay! Everything went well!
  }, 3000);
       }).on('error', (error) => {
         var errMessage = "error occured during subscription process.."+error
         logger.error('Error is: ', errMessage);
         throw error;
       })

    });
```
NOTE: I have gone through the advanced example but not getting clear idea how it might help in achieving my requirement.

> Hi @mayankmike86,
> 
> Thanks for posting and congrats on posting your first issue :)
> 
> I'm sorry to say, I think you've misunderstood how [RabbitMQ consumers](https://www.rabbitmq.com/tutorials/amqp-concepts.html#consumers) and [Node event emitters](https://nodejs.org/api/events.html) work. The [RabbitMQ Concepts](https://www.rabbitmq.com/tutorials/amqp-concepts.html) and [amqplib Channel API](https://www.squaremobius.net/amqp.node/channel_api.html#channel_get) (the library underpinning Rascal) are **must reads** for anyone getting started, since RabbitMQ has significant differences to other message brokers. Also check out this [advanced example](https://github.com/guidesmiths/rascal/blob/master/examples/advanced/index.js) for how you could use Rascal in an application.
> 
> That said the big issue/misunderstanding in your code centers around this line...
> 
> ```js
> await result.on('message', (message, content, ackOrNack) => {
> ```
> 
> `result` is an event emitter, and the `result.on` function is **synchronous**, immediately returning the same instance of the emitter to enable chaining. The message event handler `(message, content, ackOrNack) => { ... }` is invoked whenever a message is received. i.e. it is designed to be called multiple times. Awaiting `result.on` will resolve immediately, hence why your subscribe function returns undefined. `return Promise.resolve(content)` will eventually be invoked whenever a message is delivered, but only after the `subscribe` function has already returned. To do what you describe, the callee should supply the message handler, and expect it to be called multiple times (once per dequeued message).
> 
> Furthermore you've never called `ackOrNack` so the message will be left in an unacknowledged state on the broker, potentially blocking further messages (depending on your prefetch limit) and being rolled back/redelivered when your application restarts.
> 
> From the above, it looks like you don't really want to consume an infinite stream of messages, rather you want to get a single message. Rascal doesn't support this directly, but it possible using [amqplib's channel.get](https://www.squaremobius.net/amqp.node/channel_api.html#channel_get). If this is all you want to do then forget about Rascal and just use amqplib. If you do intend to use pub/sub extensively, but also need `channel.get` you can obtain an amqplib connection using Rascal's [broker.connect](https://github.com/guidesmiths/rascal#connect), but you won't get the benefit of Rascal's connection recovery logic and should remember to disconnect.

**Comment by mayankmike86** [comment]
Is it possible to achieve what i am trying to do. Or in rascal we can just log stream of messages and can not accumulate them in array to pass on for further usage?

**Comment by cressie176** [comment]
Hi @mayankmike86,

I guess what would really help if I could get a high level overview of what you are trying to do, e.g.

> Our queue collects page visits at a rate of ~100 messages per second. We want to run a batch process every hour to insert them into our analytics database.

or maybe

> Our queue collects password reset requests on an adhoc basis. We want to process the request as soon as possible after receiving it.

**Comment by cressie176** [comment]
Hi @mayankmike86,

Did you get any further with this? I sense there's quite a big gap between your understanding of RabbitMQ and the solution you're suggesting. I'm very happy to help, but can't offer any meaningful advice without a better understanding of your business context.

**Comment by mayankmike86** [comment]
> Hi @mayankmike86,
> 
> Did you get any further with this? I sense there's quite a big gap between your understanding of RabbitMQ and the solution you're suggesting. I'm very happy to help, but can't offer any meaningful advice without a better understanding of your business context.

Hi @cressie176 I have reread the documentation and understand the Rabbitmq functionality. I am able to achieve my requirements by introducing a handler to my subscribe method in client which will be called for each message subscribtion. Thanks for quick replies and help.
And sorry for not updating the ticket with my findings and understanding. I am closing this now as it's working what was expected. Thanks again for your support. Happy coding.
