### ISSUE TITLE
Optimized way to close rabbitMQ connection

### ISSUE THREAD

**Issue by nik-vaidya** [guidesmiths/rascal#137]
I have a use case where I use a different rascal configuration file for publishing different messages to different exchanges respectively. So I can not use the same connection every time to publish a message. 

But by using a new connection for publishing a message every-time is causing an exceed in the maximum connection limit as we are not closing the connection.

To close the connection we come across the `broker.shutdown()` method. I tried this and I could the connections remain as is, without an increase.

can you let me know if there any other optimized way that we can stick to, in this context?

**Comment by cressie176** [comment]
Hi @nik-vaidya,

Sorry, I'm afraid I haven't managed to properly grasp the context you describe and it sounds like you might have misunderstood Rascal's architecture.

It is possible with Rascal to define multiple exchanges and vhosts within a single rascal configuration. When you start the broker, it will establish a configurable pool of permanent connections per vhost - the connections are not opened and closed each time you send a message and are perfectly safe to be shared.

I can't think of a situation where you would want to use rascal to publish a message, then shutdown the broker.

**Comment by nik-vaidya** [comment]
Apologies, let me give some more details

I am using a microservice-based setup, where I am serving the requests for multiple tenants.
I am passing the tenant identifier in the headers of the rascal configuration so that the subsequent micro service subscriber who is listening for my message will understand that the message is being published for an XYZ tenant. hence I see the problem to re-use that connection for a different tenant.

So I was looking into the ways where I can close the connection after my tenant's request has been served

**Comment by cressie176** [comment]
Thanks for the clarification. When you say "passing the tenant identifier in the headers of the rascal configuration", I assume you mean the publication configuration?

If this is the case you could you not 

1. pass the header to the `broker.publish` function
1. define two publications for the same exchange, but with a different header

Regarding connections - Rascal typically opens up one connection to a vhost (a correction to my pool comment earlier, Rascal uses a channel pool but shares a connection). There is no need to create a second connection because of the contents (header or payload) of a message, unless the connection is to a different vhost, for a different user, or requires some other connection level feature such as TLS or socket configuration.

**Comment by cressie176** [comment]
Or do you mean you are connecting to a different RabbitMQ broker, depending on the Tenant?

**Comment by nik-vaidya** [comment]
Yes depending on the tenant, it will connect to the respective broker. As for each tenant, a new broker is created

**Comment by cressie176** [comment]
Just to confirm - I don't mean Rascal Broker, I mean RabbitMQ Broker - i.e. the server. Do you have one of these per tenant?

**Comment by nik-vaidya** [comment]
Ohh sorry.

We have only one rabbitMQ server for all tenants

**Comment by cressie176** [comment]
So in this case you would usually only require 1 connection per vhost.

Typical RabbitMQ publishing usage is as follows (nothing to do with Rascal)

- RabbitMQ Broker can contain multiple Vhosts (virtual hosts)
- The client establishes a permanent connection to a vhost
- The client opens a permanent channel "within" the connection
- The client uses that channel to publish messages to an exchange or queue

With what you have described so far, you would simply use the same channel to publish messages for each tenant, and add a message header to tell the consumer which tenant the message belongs to.

With Rascal the process is somewhat similar

- Configure a vhost, exchange and publication
- Rascal will manage the connection and channels behind the scenes
- Publish a message to the publication, setting a header via the publication options, e.g.
    ```js
    broker.publish("p1", "some message", { routingKey: "some.routing.key", options: { headers: { tenant: 't1' } } });
    ```
- Alternatives you can define two publications, for the same exchange, preconfigured with the tenant id

**Comment by nik-vaidya** [comment]
Thank you so much for the information

As you said we can reuse the connection, so suppose I want to publish a message per HTTP request for a particular tenant. Initially I am creating a connection using `Rascal.BrokerAsPromised.create(Rascal.withDefaultConfig(rascalconfig))` while setting up a tenant

So when I am publishing a message I will use the `Broker` object returned by the above method and call the publish method on it.

So if I want to publish a message again when an HTTP request comes then how can I retrieve this broker object. Is any method provided by rascal to get this broker object without creating a connection(without calling create again). 

How can i reuse the connection using rascal?

**Comment by cressie176** [comment]
Hi @nik-vaidya,

My prefered way is to to initialise the broker when you start your application, then pass it to a function which initialises your middleware, then start your http server.

e.g. Something like the following

#### index.js
```js
Rascal.BrokerAsPromised.create(config)
  .then(broker => {
    const app = express();
    initRoutes(app, broker);
    app.listen((err) => {
      if (err) throw err;
      console.log('Started');
    });
  })
  .catch(err => {
    throw err;
  });
```

#### initRoutes.js
```js
module.exports = (app, broker) => {
  app.get('/publish/:tenant', (req, res) => {
    broker.publish('send', req.body, { options: { headers: { tenant: req.params.tenant } } })
      .then(() => {
        res.status(202).send();
      })
      .catch((err) => {
        res.status(500).json({ msg: err.message });
      })
  });
}
```

For the avoidance of doubt, I haven't tried running the above, so it's probably full of typos, but should be enough to get the idea across;

**Comment by nik-vaidya** [comment]
Thank you @cressie176 

I tried out passing tenant information(headers) through options and it is working.

Can rascal manage to retrieve the broker object instead of passing it to each and every route where we want to publish a message?

**Comment by cressie176** [comment]
> Can rascal manage to retrieve the broker object instead of passing it to each and every route where we want to publish a message?

No. This is the responsibility of the application.

**Comment by nik-vaidya** [comment]
Okay, thanks @cressie176 

One more query I have, how long a connection will stay alive once I create it. Is there any limit(time out)? and do I need to handle such scenarios or rascal will take care of it if the connection lost? 

As per documentation rascal supports automatic connection retries but just need to confirm regarding timeouts

Thanks in advance

**Comment by cressie176** [comment]
The connection is permanent. Rascal will not close it automatically. 

The RabbitMQ protocol includes a heartbeat, so providing this is set your connection should not timeout due to inactivity. Rascal [defaults](https://github.com/guidesmiths/rascal/blob/master/lib/config/defaults.js#L6-L7) to 10 seconds.

Rascal also defaults a connection timeout to 10 seconds. This is passed directly to RabbitMQ. You can read about it [here](https://www.rabbitmq.com/uri-query-parameters.html)

Finally you can configure a socket timeout, which also [defaults](https://github.com/guidesmiths/rascal/blob/ada6725ff939eb0fef2de58bf59a5f6e92473b8c/lib/config/defaults.js#L10-L12) to 10 seconds.

If you encounter a connection error (e.g. a timeout) while first initialising the broker, Rascal will try the next node in the cluster (assuming you are using a RabbitMQ cluster). If all nodes fail, then Rascal will yield an error. 

If you encounter a connection error after successfully initialised the broker, Rascal will continue cycling through nodes attempting to re-establish a connection and keep looping through forever, but backing off exponentially between attempts up to a maximum interval.

**Comment by nik-vaidya** [comment]
Okay, Thank you so much @cressie176  for this information. It was a great help!
