### ISSUE TITLE
Subscriber is getting all messages from queue irrespective of the defined routing key!

### ISSUE THREAD

**Issue by collaboratorassignment** [guidesmiths/rascal#139]
Hello Team,

We have used Rascal for publishing message to a queue **emp.lifecycle.notify** with different routing keys for example
```js
broker.publish("emp", "message", "someID.employee.creat"); 
broker.publish("emp", "message", "someID.address.create");`
```

1. First routing keys for employees as--> **someID.employee.create**
2. Second routing keys for address as --> **someID.address.create**

Now messages are published on **emp.lifecycle.notify** with above routing keys respectively.
But the problem is when subscriber is subscribing the queue with first routing key, they are getting all the messages in the queue irrespective of routing key. Is this the expected behaviour of **rascal/rabbitmq** or they should be getting only the messages for the specific routing key.
Please help. In case we want to achieve above scenario to get only messages from queue for a particular routing key, do we need to change some configuration or we need to implement individual queues for each routing key?

NOTE: My rascal configuration used for connection is filled with below constants.

```js
const EXCHANGE = ["emp.lifecycle"]
const QUEUES = ["emp.lifecycle.notify"]
const BINDINGS= ["emp.lifecycle[*.*.*] -> emp.lifecycle.notify"]
const PUBLISH = { "emp": { "exchange": "emp.lifecycle", "routingKey": "*.*.*" } };`
```

PS: I can see one binding as  `*.*.*` getting created inside exchange for queue and routing key, is this somehow causing the issue, if yes how I can avoid it by changing my configuration.

Regards
Mayank

**Comment by cressie176** [comment]
Hi Mayank,

This is highly likely to be your configuration, and I suspect you might have misunderstood RabbitMQ routing. The first thing to check is that you are publishing to a "topic" exchange. This is Rascal's default, but if you have the RabbitMQ management plugin installed it is worth checking from the web based UI.

Next you need to understand the routing keys used for publishing. In the above example it appears you have configured the publication a routing key of `".*.*`. You normally wouldn't include wildcards in a routing key when publishing (I suspect they are probably treated literally). Instead use a specific routing key, e.g. `1234.user`. However, you don't appear to be using this routing key since you override it when calling `broker.publish`. Here you specify `someID.employee.created`, which is fine.

When you subscribe to filter messages, when you bind the queue to the exchange you will need to specify a binding key. To receive only the employee messages you would specify `${exchange}[*.employee.*] => ${queue}`. To receive just the employee create messages you would specify `${exchange}[*.employee.create]=> ${queue}`. However your binding key is `[*.*.*]` meaning `anything.anything.anything` will be routed to the queue.

To fix this you will need to update your configuration and manually delete the incorrect binding. Rascal won't do this last part automatically.

**Comment by cressie176** [comment]
Did you manage to get this working?
