### ISSUE TITLE
Remove broker configuration duplication in publisher and consumer

### ISSUE THREAD

**Issue by kkhanhluu** [guidesmiths/rascal#146]
For each publisher or consumer application, i have to duplicate some configuration i.e. queues, exchanges, bindings configuration. Is there any elegant way to remove these duplication? so that publisher/consumer only have configuration of publications/subscriptions. 

What i have tried is to create a json defnition file with all exchanges, queues and bindings needed by broker. Then starting rabbitMQ broker with this definition file and add rascal subscriptions, publications configuration for my publisher/consumer. With this approach i get error because configure.js file needs to know the queue's name from rascal configuration.

**Comment by cressie176** [comment]
Hi @kkhanhluu,

Unfortunately there's nothing in Rascal right now that would support this, but I can see how it would be useful. I'm. not sure how easy it would be to add though, but will give it some though.

The best thing to do in the meantime would be to either maintain a shared json document for the queues, exchanges and bindings, and programatically merge that into the application specific configuration (containing the publisher/subscribers), before passing it to Rascal.

**Comment by cressie176** [comment]
Hi @kkhanhluu,

I was thinking about this some more, and remembered the reason Rascal is designed this way. If the queues, exchanges and bindings are not defined per application, then I suspect TDD and local application development would become cumbersome. Every time a developer needed to publish or consume a new message, they would manually have to create it locally, then somehow sync it with the other members of the development team and CI/CD pipelines.

How do you currently do things like this in your environment?

**Comment by kkhanhluu** [comment]
Thanks for your quick reply. As you said, we have a shared json definitions for the message broker and each application knows exactly to which queues it should be connected to. Why do I have to create queue manually locally when i need to publish a new message?

**Comment by cressie176** [comment]
It's possible that I'm just not familiar with your software development process. The process I tend to follow is...

1. Define the queues / exchanges / bindings in source controlled application config (so Rascal will auto create them on application start and/or during integration tests)
2. Test drive the feature which uses the queues / exchanges / bindings (RabbitMQ runs locally in docker)
3. Commit & push the code
4. Continuous integration will pull and test the application. Because the queues / exchanges / bindings are part of the source code, Rascal will automatically create them when running the integration tests
5. Deploy the application. Rascal will automatically create the queues / exchanges / bindings when the application starts

This also has the advantage that when another developer pulls my changes, and starts the application / runs the integration tests locally, all the queues / exchanges / bindings are automatically created on their personal instance of RabbitMQ (running in docker)

**Comment by cressie176** [comment]
@kkhanhluu,

Sorry - I just read my last comment and realised I didn't phrase it as a question...

Under what circumstances is Rascal useful without automatically setting up queues, exchanges and bindings?

**Comment by kkhanhluu** [comment]
@cressie176 

sorry for my late response. I'm actually in vacation so i do not check my email and github frequently. 

The flow you mentioned above is what we are following and defining queues/exchange/bindings in code, of course, makes testing easier. But for the production environment, where the list of queues/exchange/bindings should be pre-defined, there will be configuration duplication as i said my question in each application. 

I just came up with the question when i read through the codebase of each application and spot the duplication. I actually haven't thought how to deal with it in CI/CD pipelines without defining exchange/bindings/queues with rascal.

**Comment by cressie176** [comment]
> But for the production environment, where the list of queues/exchange/bindings should be pre-defined, there will be configuration duplication

Have you considered allowing Rascal to create the queues, exchanges and bindings in production too? To me this is quite important as it guarantees that the necessary resources will be in place when the application is deployed, without an additional step. It should also be more reliable since it is guaranteed to be the same setup as all your other environments, and the creation process has run repeatedly locally, on CI and in all prior environments.

However, if this is not possible or desirable, then I recommend overriding your production configuration so that the queues and exchanges are "checked" instead of "asserted". That way Rascal will still ensure they exist. Unfortunately there's no way to check the bindings.

> Of course, makes testing easier. But for the production environment, where the list of queues/exchange/bindings should be pre-defined, there will be configuration duplication

I understand better now. I manage config in a hierarchical way using [confabulous](https://github.com/guidesmiths/confabulous). There's a default configuration, which is checked into with the source code, and that contains the common configuration. Then there's environment specific configuration for local, build, development, staging and production. Application secrets are managed securely outside of source control and injected at deployment time. Consequently there's very little duplication.

**Comment by cressie176** [comment]
Also - just checking, are you aware of the [shorthand configuration](https://github.com/guidesmiths/rascal#shorthand-notation) and default publications/consumers? They can help reduce configuration considerably.

**Comment by kkhanhluu** [comment]
Yeah. I already used the shorthand configuration. Thanks again for being so supportive and for your contribution to this awesome library. I will discuss again with my team. If we come up with any other solution, i will immediately inform you about it.

**Comment by cressie176** [comment]
Thanks @kkhanhluu
