### ISSUE TITLE
Retry subscription when queue not found

### ISSUE THREAD

**Issue by nhitchins** [guidesmiths/rascal#160]
The subscription retry logic does not seem to work when attempting to subscribe to a queue that does not (yet) exist. 

It throws the subscription error `BasicConsume; 404 (NOT-FOUND) with message "NOT_FOUND - no queue..."` and does not retry. Is this expected behaviour? 

The queue config has `assert=false` and `check=false` as another service is responsible for managing the queue, but I need to be able to subscribe to it when it comes available. Any ideas?

**Comment by cressie176** [comment]
Hi @nhitchins,

Yes, it is expected behaviour. Rascal wasn't designed with dynamic environments in mind and doesn't support them very well. Have you tried repeated calling `subscribe` until it works (using something like [p-retry](https://www.npmjs.com/package/p-retry) or [async.retry](https://caolan.github.io/async/v3/docs.html#retry)?

I'm also curious about why the queue doesn't exist (yet), and why it needs to be managed by another service. Where possible publish to an exchange (definition repeated in both publisher and consumer) and make the consumer responsible for the queue + binding.

**Comment by nhitchins** [comment]
Thanks. That makes sense - just ensuring we are leveraging the capabilities of rascal prior to adding our own retry logic. 

ps. Its a shared queue which may not (yet) exist in a clean test environment when starting a few services in parallel, but thats easily worked around by staggering the deployments
