### ISSUE TITLE
(Question) Is there a way to use exponential backoff in recovery strategies

### ISSUE THREAD

**Issue by carlosvillademor** [guidesmiths/rascal#169]
Hi @cressie176, I hope you are doing well mate. I was wondering whether there is a way to use an exponential backoff when using the recovery strategies.

So we could use something similar to the settings used for the connection.retry in

```js
{
	  "vhosts": {
		    "v1": {
			      "connection": {
				        "retry": {
				          "min": 1000,
				          "max": 60000,
				          "factor": 2,
				          "strategy": "exponential"
				        }
			      }
		    }
	  }
}
```

When setting recovery configuration, so instead of:

```js
"recovery": {
	  "deferred_retry": [
		    {
			    "strategy": "republish",
			    "defer": 5000,
			    "attempts": 3
		    },
		    {
		    	"strategy": "nack"
		    }
	  ]
}
```

we could have something like: 

```js
"recovery": {
	  "deferred_retry": [
		    {
			    "strategy": "republish",
			    "min": 1000,
				"max": 60000
			    "factor": 2
		    },
		    {
		    	"strategy": "nack"
		    }
	  ]
}
```

**Comment by cressie176** [comment]
Hi @carlosvillademor,
Finally got around to looking at this, and on reflection, I don't think it is worth the complexity and inconsistency. Currently the `defer` option is compatible with any recovery strategy and is [implemented](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/SubscriberError.js#L18-L32) universally. An exponentially increasing deferral period would only be applicable to a subset of strategies (the ones which can be attempted multiple times), so the deferral logic would have to be made specific, and I would rather not complicate it.

A second consideration is that since `defer` delays publishing via setTimeout and Node's event loop, I'm reluctant to encourage this for long periods of time - if there were a lot of errors it could end up choking application or causing it to run out of memory.

**Comment by carlosvillademor** [comment]
Thanks for the feedback @cressie176
