### ISSUE TITLE
Deleting queues and subscription on demand

### ISSUE THREAD

**Issue by SaiKrishnaMaddu** [guidesmiths/rascal#189]
can we delete the queues and subscriptions on demand as in we need to delete queues from the rabbitMQ console permanently

**Comment by cressie176** [comment]
Hi @SaiKrishnaMaddu,

You can obtain a raw connecting using the [vhost.connect](https://github.com/guidesmiths/rascal#connect) function, then using the underlying [amqplib api](https://amqp-node.github.io/amqplib/channel_api.html). It's not really what Rascal was intended for though, since Rascal is config driven, so any queues you define in config will be recreated the next time the application is restarted (depending on your configuration).

An alternative would be to call [broker.nuke](https://github.com/guidesmiths/rascal#nuke-purge-and-unsubscribeall) which will destroy everything Rascal has created, but this was only intended to be called for local test environments.

**Comment by SaiKrishnaMaddu** [comment]
@cressie176 Thank you for responding 

we don't want to restart the application (nodeJS App), but we want to delete add and delete the queues on demand, are you suggesting to recreate the broker again by removing the unwanted queues and subscriptions from rascalConfig?

**Comment by cressie176** [comment]
Hi @SaiKrishnaMaddu 

> we want to delete add and delete the queues on demand

Rascal isn't appropriate for this use case. It's config driven, so queues and exchanges are intended to be created on initialisation. Your best option is to use amqplib directly instead of Rascal.
