### ISSUE TITLE
Customize consumer tag

### ISSUE THREAD

**Issue by nico3dfx** [guidesmiths/rascal#209]
Hi,
in Rascal the consumer tag starts with "amq.ctag-*".

Is it possible to customize all or part of the name?

Thank you,
Nico.

**Comment by nico3dfx** [comment]
The consumerTag key can be configured inside the single subscription:

```
"subscriptions": {
    "test123": {
          "queue": "test123_queue",
                "options": {
                    "consumerTag": "test123_ctag"
                }
            }
    }
```
Not present in json schema file but the key dosen't invalidate the config.

**Comment by cressie176** [comment]
Hi @nico3dfx,

> in Rascal the consumer tag starts with "amq.ctag-*".

As you're no doubt aware, Rascal is a wrapper around [amqplib](https://github.com/amqp-node/amqplib), which is a [RabbitMQ](https://www.rabbitmq.com/) client, and therefore uses the [AMQP 0.9.1 protocol](https://www.rabbitmq.com/protocol.html). In the case of the consumer tag, it's actually RabbitMQ which will generate the value by default, unless the client provides one.

If you read the [amqplib channel api consume documentation](https://amqp-node.github.io/amqplib/channel_api.html#channel_consume) you will see this reiterated. However you can specify a consumerTag if you want to. When it comes to Rascal, there is usually an `options` object, which will be passed directly through to the equivalent amqplib function, both from config, and programmatically, with the latter taking precedence. e.g.

```
"subscriptions": {
  "test123": {
    "queue": "test123_queue",
      "options": {
        "consumerTag": "test123_ctag"
      }
    }
  }
} 
```

```
await subscription = broker.subscribe("s1", { consumerTag: "test123_ctag" })
```
In this case though I didn't include the property in the JSON schema, probably because it's I've never found a reason to hard code it. I don't think there will be an issue with setting as you have done though. I'll update the JSON schema accordingly.
