### ISSUE TITLE
How can I do multi-ack?

### ISSUE THREAD

**Issue by mortiy** [guidesmiths/rascal#212]
Hi,
Is this functionality exposed in Rascal?
https://www.rabbitmq.com/confirms.html#consumer-acks-multiple-parameter

**Comment by cressie176** [comment]
Hi @mortiy,

It's not currently possible with Rascal. I'm not against adding it. Currently `ackOrNack` takes no arguments when you want to acknowledge, and an error object plus optional recovery config if you want to handle a problem, e.g. `ackOrNack(err, { strategy: 'requeue' })`. Changing the API accept a boolean in place of the error object to signify multiple acknowledgments, i.e. `ackOrNack(true)` would be a potential, but dangerous option as current versions of Rascal only check with the error parameter is truthy, and I suspect will nack the message if passed true. This would mean that any existing client code which passed a truthy, non-error value, would start acknowledging messages instead of nacking them.

A safer alternative would be to pass null or undefined for the error argument, and a config object as an optional second parameter. e.g. `ackOrNack(null, { multiple: true })`. Providing I catered for the optional callback, I think this would work well.

I'm happy to spend some time on it, or accept a tested PR (I can provide guidance), but before going further, would like to understand why you are interested in this feature. I've never found any use for multiple acknowledgements, which is why it's been overlooked until now.

**Comment by mortiy** [comment]
Hi @cressie176,
>  why you are interested in this feature.

I'm implementing AMQP messages batching for my task.
So I'm pre-fetching, for example, 1000 messages (without ack), collect them into single batch and process in a whole.
When I'm done (with successful result), I need acknowledge all of them.
Right now, I have to keep all 1000 `ackOrNack` function references to do that, but with multi-ack I could keep only the last one.

**Comment by cressie176** [comment]
OK, that makes sense. Thank you

**Comment by cressie176** [comment]
```js
ackOrNack(null, { all: true })
```

or

```js
ackOrNack(err, { strategy: 'nack', all: true })
```

**Comment by cressie176** [comment]
@mortiy OK to close?

**Comment by mortiy** [comment]
Yes, thank you.
