### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined

### ISSUE THREAD

**Issue by Fxlr8** [guidesmiths/rascal#32]
Hi, I was trying to add rascal to my project. Here is my code based on `examples/simple`
```js
const config = {
	'vhosts': {
		'v1': {
			'connection': 'amqp://localhost'
		}
	}
}

Rascal.Broker.create(Rascal.withDefaultConfig(config), function(err, broker) {
	if (err) throw err
        console.log(broker)
})
```

here is the traceback
```
blah/node_modules/async/dist/async.js:228
    return supportsSymbol && fn[Symbol.toStringTag] === 'AsyncFunction';

                               ^

TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined
    at isAsync (/Somewhere/over/the/rainbow/node_modules/async/dist/async.js:228:32)
    at wrapAsync (/Somewhere/over/the/rainbow/node_modules/async/dist/async.js:232:12)
    at arrayMap (/Somewhere/over/the/rainbow/node_modules/async/dist/async.js:1687:21)
    at seq (/Somewhere/over/the/rainbow/node_modules/async/dist/async.js:2564:22)
    at Object.compose (/Somewhere/over/the/rainbow/node_modules/async/dist/async.js:2624:16)
    at new Broker (webpack:///./node_modules/rascal/lib/amqp/Broker.js?:35:20)
    at eval (webpack:///./node_modules/rascal/lib/amqp/Broker.js?:21:7)
    at /Somewhere/over/the/rainbow/node_modules/async/dist/async.js:2583:16
    at /Somewhere/over/the/rainbow/node_modules/async/dist/async.js:473:16
    at /Somewhere/over/the/rainbow/node_modules/async/dist/async.js:2521:9
```
Node v10.10.0
rascal v3.2.0

Looks like the lib is broken

**Comment by cressie176** [comment]
Hi @Fxlr8,

Sorry your having problems, and thanks for reporting. The [tests](https://travis-ci.org/guidesmiths/rascal/jobs/425260692) and simple example works fine with node 10
```
cd simple/
euphrosyne:simple $ node index.js 
2018-10-07T06:49:36.300Z: hello world
2018-10-07T06:49:37.304Z: hello world
2018-10-07T06:49:38.306Z: hello world
^C
euphrosyne:simple $ node --version
v10.1.0
```
So I suspect there's something different with your local setup. If you google for that error message [you'll see](https://github.com/caolan/async/issues/1427) it can occur when a function is not passed to async. Your stack trace points to [this line](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Broker.js#L35)

```
var init = async.compose(tasks.initShovels, tasks.initSubscriptions, tasks.initPublications, tasks.initCounters, tasks.initVhosts);
```

This line initialises rascal by running through a series of functions asynchronously. When I physically insert a null anywhere in this list I get the same error as you do. All of these functions are exported [here](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/tasks/index.js#L4-L7) using require-all.
```
fs.readdirSync(__dirname).filter(byTask).forEach(function(fileName) {
  var moduleName = fileName.replace(/\.js$/, '');
  exports[moduleName] = require(path.join(__dirname, fileName));
});
```
I suspect that for some reason the tasks are being filtered out in your environment. Is there anything in your build process that could be renaming them so that they don't end in `.jsx` or moving them to a different directory? It's always possible this might be a filesystem / os difference. I develop on a macbook, and run rascal on linux, but if you're using windows maybe that could be contributing?

Are you able to add some debug to the above and confirm my suspicion?

**Comment by Fxlr8** [comment]
Hi, @cressie176, thanks for a quick response.

I use webpack to build my project, transpile it with babel and run it on a MacBook. 
I added this line right before `async.compose` call to see what task is missing
```js
  console.log(typeof tasks.initShovels, typeof tasks.initSubscriptions, typeof tasks.initPublications, typeof tasks.initCounters, typeof tasks.initVhosts)
  var init = async.compose(tasks.initShovels, tasks.initSubscriptions, tasks.initPublications, tasks.initCounters, tasks.initVhosts);
```
And each of them is missing
```
undefined undefined undefined undefined undefined
```

Also, i found this warning from webpack
```
WARNING in ./node_modules/rascal/lib/amqp/tasks/index.js 6:24-63
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/rascal/lib/amqp/Broker.js
 @ ./node_modules/rascal/index.js
 @ ./src/server/index.js
```

**Comment by Fxlr8** [comment]
Never mind. I forgot to restart webpack watch script after i installed a new package. Stupid me! Thanks for help. Everything is fine now

If somebody else gets this kind of warning, don't forget to use `nodeExternals` plugin with webpack and exclude `node_modules` from babel

**Comment by cressie176** [comment]
Thanks for coming back and the tip about `nodeExternals`.  Shout if you need any more help.
