### ISSUE TITLE
prefetch: set global flag in config.js

### ISSUE THREAD

**Issue by mced** [guidesmiths/rascal#33]
I'd like to know if it is possible to set `global` flag in `prefetch` setting from amqplib[1] and if so, how ?

[1] http://www.squaremobius.net/amqp.node/channel_api.html#channel_prefetch

**Comment by mced** [comment]
That would be awesome, thanks!

**Comment by cressie176** [comment]
Hi @mced. I was looking into this more closely. Making the configure support global is no problem, but I was wondering how it would help you. Rascal creates a new channel per subscription, so there will always be exactly 1 consumer per channel. 

If I understand the purpose of global it was to set the prefetch count per channel, rather than per consumer, but since this is a one-to-one mapping I don't see it would make any difference.

**Comment by mced** [comment]
If I understand correctly, prefetch global flag set to true will apply the prefetch count to channel while set to false will apply prefetch count to consumer.

Indeed you're right if Rascal creates a new channel per susbscription, that won't change anything...
