### ISSUE TITLE
How to handle RPC communication?

### ISSUE THREAD

**Issue by akeyboardlife** [guidesmiths/rascal#45]
Sorry to ask this silly question.

I saw the publication.on('return') event listener, but can't figure out how to return message from the subscription.

**Comment by cressie176** [comment]
Hi @akeyboardlife,

Sorry I don't follow...

RabbitMQ `returns` messages that you publish when they aren't routed to a queue. You can't `return` a message from a subscription, since at this point you're consuming not publishing.

Assuming you mean how do I consume messages from a subscription, then you need to use the the `message` event. There's an example [here](https://github.com/guidesmiths/rascal/blob/master/examples/simple/index.js#L7-L13).

**Comment by akeyboardlife** [comment]
Sorry about that, actually I mean how can I accomplish a [RPC call](https://www.rabbitmq.com/tutorials/tutorial-six-javascript.html). Is there any wrapper from Rascal?

**Comment by cressie176** [comment]
There's nothing* in Rascal to support this, but you can still use the amqp protocol by setting replyTo and correlationId properties when you make the request, and publishing to the replyTo queue (including the correlationId) when sending the response. I knocked up a quick example...

#### Config
```js
module.exports = {
  "rascal": {
    "vhosts": {
      "/": {
        "exchanges": [],
        "queues": {
          "request": {},
          "response": {
            "options": {
              "exclusive": true
            }
          }
        }
      }
    }
  }
}
```

### Code
```
var Rascal = require('../..')
var config = require('./config')

Rascal.Broker.create(Rascal.withDefaultConfig(config.rascal), (err, broker) => {
  if (err) bail(err)

  broker.on('error', console.error)

  broker.subscribe('/request', (err, subscription) => {
    if (err) return bail(err)
    subscription
      .on('message', (message, content, ackOrNack) => {
        console.log('Received request', message);
        broker.publish('/', { msg: 'pong' }, {
          routingKey: message.properties.replyTo,
          options: {
            correlationId: message.properties.correlationId,
          }
        }, (err, publication) => {
          if (err) return console.log(err.message)
          publication.on('error', console.error)
          ackOrNack(err);
        })
      }).on('error', console.error)
  })

  broker.subscribe('/response', (err, subscription) => {
    if (err) return bail(err)
    subscription
      .on('message', (message, content, ackOrNack) => {
        console.log('Received response', message);
        ackOrNack();
      }).on('error', console.error)
  })

  setTimeout(() => {
    broker.publish('/request', { msg: 'ping' }, {
      options: {
        replyTo: 'response',
        correlationId: '1',
      },
    }, (err, publication) => {
      if (err) return console.log(err.message)
      publication.on('error', console.error)
    })
  }, 1000);

  process.on('SIGINT', function() {
    broker.shutdown(function() {
      process.exit()
    })
  })
})

function bail(err) {
  console.error(err)
  process.exit(1)
}
```

**Comment by akeyboardlife** [comment]
Thank you for the detailed explanation. And thank you for the patience.

**Comment by cressie176** [comment]
You're welcome. I wrote [stashback](https://github.com/guidesmiths/stashback) for temporarily stashing callbacks using correlationId. It's a bit old now, but might be useful.

**Comment by test544** [comment]
While i do can use default "replyTo" for rpc, the example above use static queue names, which doesn't seems usable.
I can't find any info about server-named queues in rascal. Is possible? If so - how?

**Comment by cressie176** [comment]
Hi @test544,

I wasn't aware of [sever-named queues](https://www.rabbitmq.com/queues.html#server-named-queues), and these are unfortunately not supported by Rascal. I suspect it would be possible to update Rascal's model to use a blank name instead of the given one, but am less sure how this would work with the channel pooling. Even if you limited the pool size to 1, I believe the generic-pool library may reap inactive channels.

As an alternative [if it was possible to make the queue name unique](https://github.com/guidesmiths/rascal/blob/6b995be2515600dfc5e2cbed6cd3408b8366706d/test/config.tests.js#L806-L825), on the client side would this be sufficient?

**Comment by test544** [comment]
Thanks for reply.
Tbh it's my first time using amqp at all, so i can't say anything about efficiency of this approach, but for my particular task client-generated names that is guaranteed(at least to some extent) to have no collisions with existing queues seems will be enough.

**Comment by test544** [comment]
Oh, took me a bit to get what you meant by second link. Just tested it - it partially works:

Adding "replyTo:true" does add uuid to queue name and does work if i define publication directing to "queue". But it doesnt work when I defining exchange with binding exchange->queue and publication directing to this "exchange". (my exchange works fine when i remove "replyTo:true" definition

**Comment by cressie176** [comment]
> Though I noticed that this queue still can't be used as a regular queue because when it's used for binding "exchange->queue" uuid is also added as a prefix of routingKey, which is, probably, undesirable

I'll check this out

**Comment by cressie176** [comment]
I suspect my reasoning was that if you don't prefix the routingKey with the UUID, then multiple instances of the application would replicate the binding, e.g.

### Instance 1
exchange[a.b.c] -> queue:ae9eb22c-71ec-4421-b809-aea5fdc5380f

### Instance 2
exchange[a.b.c] -> queue:737d58e2-3212-43d5-ba84-4f6101f15fee

With the above, if I was to publish a message to the exchange using `a.b.c` as the routing key, it would be delivered to both queues. I can't think of a legitimate reason for doing this that wouldn't be solved by spinning up a second non-replyTo queue.

With the uuid added to the routing key as follows...

### Instance 1
exchange[ae9eb22c-71ec-4421-b809-aea5fdc5380f.a.b.c] -> queue:ae9eb22c-71ec-4421-b809-aea5fdc5380f

### Instance 2
exchange[737d58e2-3212-43d5-ba84-4f6101f15fee.a.b.c] -> queue:737d58e2-3212-43d5-ba84-4f6101f15fee

I can publish a reply via the exchange and still have it delivered to the correct queue. That said, I'm not sure why anyone would do this instead of publishing it directly to the queue instead.

**Comment by test544** [comment]
> Can you explain why you don't want the uuid added to the routing key?
No real reason. It's just a messy setup that i got while i was testing "replyTo:true", and it didn't work. 

> I'm happy to consider proposals for how to better handle replyTo queues in Rascal though
I finally managed to make my setup work and now can apply it to a real task. So the only proposal i have is to add some info about how to implement [tutorial six](https://www.rabbitmq.com/tutorials/tutorial-six-javascript.html) via rascal to readme.

**Comment by cressie176** [comment]
I'll add some documentation to the README about replyTo. (It's actually an undocumented feature, that I thought wasn't useful and was thinking about removing, so thank you for raising)

**Comment by cressie176** [comment]
@test544 I had another thought - while Rascal will suffix a "replyTo" queue with a uuid and also add the uuid to queue bindings, I didn't find anything either automatically or manually allows the uuid to be copied into the correlationId of an outbound message. Without this Rascal's replyTo feature is pretty useless, since the application that creates the queue won't be able to advertise it to those sending the replies.

You said you managed to get your setup working. Am I wrong about the above?

**Comment by test544** [comment]
Not sure if i got your problem right, but [here](https://github.com/test544/rascal-rpc-example) is the minimized example of what i got

**Comment by cressie176** [comment]
Thanks @test544,
I'll see if I can make it more automated.

**Comment by test544** [comment]
@cressie176 hello again. 
Talking about prefixing of routing keys for exchanges, i've found a scenario where it's undesirable in (tutorial-three)[https://www.rabbitmq.com/tutorials/tutorial-three-javascript.html).

> I can't think of a legitimate reason for doing this that wouldn't be solved by spinning up a second non-replyTo queue.
In short, i want that every app subscribed to exchange to receive all of its messages. As i can see, this cannot be achieved by predefined non-unique queues, so current implementation of replyTo makes such scenario impossible.

Though ultimately i can probably live without it

**Comment by cressie176** [comment]
I'm OK removing the uuid routing key prefix. replyTo is an undocumented feature so I very much doubt anyone is using it

**Comment by cressie176** [comment]
One way to solve your problem is to publish messages with a second routing key, using the "CC" option.

I did this with a system which archived every non GDPR/PII message to S3, simply by adding the CC routing key of "archive", and binding all topic exchanges to an archive queue.

**Comment by test544** [comment]
I should been specified that "rpc" and "receive all messages from exchange" was two unrelated tasks so i'm fine with separate queue for each task. The only thing they have in common is the need for replyTo's unique queues. 

But nevertheless thank you, i'll keep that solution in mind if i come across of such task.

**Comment by cressie176** [comment]
I'ad added basic RPC support into Rascal@16. To use it...

1.  Mark as queue with  `"replyTo": true` to get rascal to automatically add the uuid (as before)
2.  Reference the queue from your publication, by setting "replyTo" to the queue name. 

This will cause Rascal to automatically set the replyTo property on any message published using that publication.

```json
{
  "queues": {
    "q1": {
      "replyTo": true
    }
  },
  "publications": {
    "exchange": "e1",
    "replyTo": "q1"
  }
}
```

**Comment by cressie176** [comment]
I also stopped Rascal messing with the binding keys

**Comment by shlomisas** [comment]
> I'ad added basic RPC support into Rascal@16. To use it...
> 
> 1. Mark as queue with  `"replyTo": true` to get rascal to automatically add the uuid (as before)
> 2. Reference the queue from your publication, by setting "replyTo" to the queue name.
> 
> This will cause Rascal to automatically set the replyTo property on any message published using that publication.
> 
> {
>   "queues": {
>     "q1": {
>       "replyTo": true
>     }
>   },
>   "publications": {
>     "exchange": "e1",
>     "replyTo": "q1"
>   }
> }

This is nice but very limited, assume i have 2 services and i need to:

1. From `Service 1, Node 1` send a queue job and get async answers back to `Service 1, Any Node`
2. From `Service 1, Node 1` send a queue job and get async answers back to `Service 1, Node 1`
3. From `Service 1, Node 1` send a queue job and get sync (RPC) answer back to `Service 1, Node 1`

With Rascal i found i can support only #1 and #3 but for 2 it's a big mess instead of just having an option to give `replyTo` to every message i'm producing and the other side will get the full exclusive queue name (include the UUID) and reply to it. 

Any idea what i can do?

**Comment by cressie176** [comment]
Hi @shlomisas,

I think you may have misunderstood Rascal's replyTo feature. It's equally possible that I have misunderstood the problem you are having, so please bear with me.

In the scenario where any instances of Service 1 can publish a message to a queue, and any instance of Service 1 can also handle a responses from Service 2, the easiest thing is to configure a pair of static queues, e.g. `job_queue` and `answer_queue`, used by all instances of Service 1 and Service 2. You can do this with Rascal just regular queue, publication and subscription configuration.

However, if the response needs to be routed to the same instance of Service 1 that published the original message, then you can use Rascal's replyTo configuration. This will create a dedicated queue per instance of Service 1 differentiated by a uuid, and automatically include the queue name in the RabbitMQ replyTo message property. The consumer has to use this property in order to know where to send the reply.

If you don't want to or can't use static (i.e. configuration time, rather than runtime) queues, then an instance of Service 1 will need to dynamically create the queue, and include the queue name in the message it publishes to the job queue, possibly in the message body, a custom property, or ideally the RabbitMQ replyTo property. All instances of Service 1 will need to consume from the dynamically created queue (how they learn about it is a challenge). Service 2 will have to extract the queue name from the message and publish the answer to it. Rascal has very limited support dynamic queue creation without jumping through a lot of hoops. You can obtain a reference to the connection, and create them yourself, or you could dynamically configure an instance of Rascal, but neither options are good. You may be better off with another library.

Rascal also doesn't support RabbitMQ's [direct reply-to / RPC](https://www.rabbitmq.com/docs/direct-reply-to) feature. It's unfortunately incompatible with Rascal's channel pooling.

**Comment by shlomisas** [comment]
Thanks for the detailed answer!

I was referring to use-case #2 - needing to define the `replyTo` on the fly. Rascal does provide this option via the `publish` method (though in TypeScript I need to use `@ts-ignore` since some options exist in JS but aren't exposed through types). 

The challenge is that since Rascal generates the UUID for the exclusive queue, I have to implement a workaround to get it upon subscription creation (via `subscription.config?.source` - which also requires to be under `@ts-ignore`) and save it in a mapper with the original exclusive queue name I'm providing to Rascal at configuration time. to much efforts IMO.

I believe this use-case is valid and worth considering since it primarily helps solve race conditions with series of messages coming back from Service2 to Service1 that must be processed in a certain order (e.g., in an AI-based app that replies to user messages).

Regarding RPC, I misunderstood the documentation. I thought Rascal had built-in RPC support based on this:

![Image](https://github.com/user-attachments/assets/fd55b70e-8445-4b1f-a171-a3e9eec81505)

But I see now it only supports the common headers of RabbitMQ (`replyTo` and `correlationId`) and I needed to implement the full RPC pattern myself, which is not trivial.
