### ISSUE TITLE
Can't subscribe to message of a specific type

### ISSUE THREAD

**Issue by Ibrahimtrrc** [guidesmiths/rascal#64]
Rabbit has message properties. In this properties we can put a type.
![image](https://user-images.githubusercontent.com/44973146/65670171-1c14c800-e045-11e9-823b-ece4deb79112.png)
Rabbit let you handle ( consume ) messages of a specific type so you can have multiple consumers in one application depending on the type property.

I can't manage how to do that with rascal.

Is it possible ?

**Comment by cressie176** [comment]
Hi @Ibrahimtrrc 

I wasn't aware that you could subscribe to messages that match only a specific type. It would surprise me since routing is normally the responsibility of the exchange and queue binding. In fact, the RabbitMQ [documentation](https://www.rabbitmq.com/consumers.html#message-properties) explicitly states that the message type is ignored by the broker.

> The type property on messages is an arbitrary string that helps applications communicate what kind of message that is. It is set by the publishers at the time of publishing. The value can be any domain-specific string that publishers and consumers agree on.
>
> RabbitMQ does not validate or use this field, it exists for applications and plugins to use and interpret.

Is it possible you are confusing this feature for [header](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-headers) exchanges or a non AMQP specific feature that is implemented by [another library](https://github.com/LeanKit-Labs/wascally/issues/48)?

**Comment by Ibrahimtrrc** [comment]
Hi @cressie176 ,
yes it's possible that i am confused.
Actually i was using  [rabbot](https://github.com/arobson/rabbot/blob/master/docs/receiving.md) which is using amqplib. 
But rabbot is not maintained and has some performance leaks on publish.

The solution you propose can't fit my context. I have 2 stages of routing. and i cant have one queue per message type. It will be too much ( more than 10 000 ) but if i use routing Key + message type i turn around 150 queues.

**Comment by Ibrahimtrrc** [comment]
I'll this issue as you responded to my question. 

Thanks for your availability
